# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\operator.TEACHER\Dropbox\Programming\Python\projects\recenzia\widgets\add_review_widget.ui'
#
# Created: Thu May  4 13:40:46 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(514, 572)
        self.verticalLayout_2 = QtGui.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setContentsMargins(-1, -1, -1, 6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_5 = QtGui.QLabel(Form)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 0, 0, 1, 1)
        self.cb_conformity = QtGui.QComboBox(Form)
        self.cb_conformity.setObjectName("cb_conformity")
        self.gridLayout_4.addWidget(self.cb_conformity, 1, 6, 1, 4)
        self.label_3 = QtGui.QLabel(Form)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 1, 0, 1, 1)
        self.cb_kat = QtGui.QComboBox(Form)
        self.cb_kat.setObjectName("cb_kat")
        self.gridLayout_4.addWidget(self.cb_kat, 0, 9, 1, 1)
        self.cb_group = QtGui.QComboBox(Form)
        self.cb_group.setObjectName("cb_group")
        self.gridLayout_4.addWidget(self.cb_group, 1, 1, 1, 1)
        self.label_2 = QtGui.QLabel(Form)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 0, 8, 1, 1)
        self.le_number = QtGui.QLineEdit(Form)
        self.le_number.setText("")
        self.le_number.setObjectName("le_number")
        self.gridLayout_4.addWidget(self.le_number, 0, 1, 1, 1)
        self.le_name = QtGui.QLineEdit(Form)
        self.le_name.setText("")
        self.le_name.setObjectName("le_name")
        self.gridLayout_4.addWidget(self.le_name, 0, 3, 1, 5)
        self.label = QtGui.QLabel(Form)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 2, 1, 1)
        self.label_4 = QtGui.QLabel(Form)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 1, 3, 1, 3)
        self.verticalLayout_2.addLayout(self.gridLayout_4)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabwidget = QtGui.QTabWidget(Form)
        self.tabwidget.setObjectName("tabwidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tw_part0 = QtGui.QTableWidget(self.tab)
        self.tw_part0.setObjectName("tw_part0")
        self.tw_part0.setColumnCount(0)
        self.tw_part0.setRowCount(0)
        self.verticalLayout_4.addWidget(self.tw_part0)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.tabwidget.addTab(self.tab, "")
        self.widget = QtGui.QWidget()
        self.widget.setObjectName("widget")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.tw_part1 = QtGui.QTableWidget(self.widget)
        self.tw_part1.setObjectName("tw_part1")
        self.tw_part1.setColumnCount(0)
        self.tw_part1.setRowCount(0)
        self.verticalLayout_6.addWidget(self.tw_part1)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        self.tabwidget.addTab(self.widget, "")
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.tab_4)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.tw_part2 = QtGui.QTableWidget(self.tab_4)
        self.tw_part2.setObjectName("tw_part2")
        self.tw_part2.setColumnCount(0)
        self.tw_part2.setRowCount(0)
        self.verticalLayout_8.addWidget(self.tw_part2)
        self.verticalLayout_9.addLayout(self.verticalLayout_8)
        self.tabwidget.addTab(self.tab_4, "")
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.tab_5)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.tw_part3 = QtGui.QTableWidget(self.tab_5)
        self.tw_part3.setObjectName("tw_part3")
        self.tw_part3.setColumnCount(0)
        self.tw_part3.setRowCount(0)
        self.verticalLayout_10.addWidget(self.tw_part3)
        self.verticalLayout_11.addLayout(self.verticalLayout_10)
        self.tabwidget.addTab(self.tab_5, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.tw_part4 = QtGui.QTableWidget(self.tab_3)
        self.tw_part4.setObjectName("tw_part4")
        self.tw_part4.setColumnCount(0)
        self.tw_part4.setRowCount(0)
        self.verticalLayout_12.addWidget(self.tw_part4)
        self.verticalLayout_13.addLayout(self.verticalLayout_12)
        self.tabwidget.addTab(self.tab_3, "")
        self.verticalLayout_3.addWidget(self.tabwidget)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pb_add = QtGui.QPushButton(Form)
        self.pb_add.setObjectName("pb_add")
        self.horizontalLayout.addWidget(self.pb_add)
        self.pb_del = QtGui.QPushButton(Form)
        self.pb_del.setObjectName("pb_del")
        self.horizontalLayout.addWidget(self.pb_del)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        self.line = QtGui.QFrame(Form)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pb_dict = QtGui.QPushButton(Form)
        self.pb_dict.setObjectName("pb_dict")
        self.gridLayout.addWidget(self.pb_dict, 1, 3, 1, 1)
        self.label_8 = QtGui.QLabel(Form)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 2, 0, 1, 1)
        self.dateEdit = QtGui.QDateEdit(Form)
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setTimeSpec(QtCore.Qt.LocalTime)
        self.dateEdit.setObjectName("dateEdit")
        self.gridLayout.addWidget(self.dateEdit, 4, 1, 1, 1)
        self.pb_ok = QtGui.QPushButton(Form)
        self.pb_ok.setObjectName("pb_ok")
        self.gridLayout.addWidget(self.pb_ok, 4, 3, 1, 1)
        self.label_10 = QtGui.QLabel(Form)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 4, 0, 1, 1)
        self.cb_rank = QtGui.QComboBox(Form)
        self.cb_rank.setObjectName("cb_rank")
        self.gridLayout.addWidget(self.cb_rank, 3, 1, 1, 1)
        self.label_11 = QtGui.QLabel(Form)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 5, 0, 1, 1)
        self.pb_cancel = QtGui.QPushButton(Form)
        self.pb_cancel.setObjectName("pb_cancel")
        self.gridLayout.addWidget(self.pb_cancel, 5, 3, 1, 1)
        self.cb_position = QtGui.QComboBox(Form)
        self.cb_position.setObjectName("cb_position")
        self.gridLayout.addWidget(self.cb_position, 2, 1, 1, 1)
        self.label_9 = QtGui.QLabel(Form)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 3, 0, 1, 1)
        self.label_7 = QtGui.QLabel(Form)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 0, 1, 1)
        self.pb_print = QtGui.QPushButton(Form)
        self.pb_print.setObjectName("pb_print")
        self.gridLayout.addWidget(self.pb_print, 2, 3, 1, 1)
        self.label_6 = QtGui.QLabel(Form)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 2)
        self.cb_rezult = QtGui.QComboBox(Form)
        self.cb_rezult.setObjectName("cb_rezult")
        self.gridLayout.addWidget(self.cb_rezult, 5, 1, 1, 1)
        self.label_12 = QtGui.QLabel(Form)
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 5, 2, 1, 1)
        self.cb_name = QtGui.QComboBox(Form)
        self.cb_name.setObjectName("cb_name")
        self.gridLayout.addWidget(self.cb_name, 1, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)

        self.retranslateUi(Form)
        self.tabwidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.le_number, self.le_name)
        Form.setTabOrder(self.le_name, self.cb_kat)
        Form.setTabOrder(self.cb_kat, self.cb_group)
        Form.setTabOrder(self.cb_group, self.cb_conformity)
        Form.setTabOrder(self.cb_conformity, self.tabwidget)
        Form.setTabOrder(self.tabwidget, self.tw_part0)
        Form.setTabOrder(self.tw_part0, self.pb_add)
        Form.setTabOrder(self.pb_add, self.pb_del)
        Form.setTabOrder(self.pb_del, self.cb_name)
        Form.setTabOrder(self.cb_name, self.cb_position)
        Form.setTabOrder(self.cb_position, self.cb_rank)
        Form.setTabOrder(self.cb_rank, self.dateEdit)
        Form.setTabOrder(self.dateEdit, self.cb_rezult)
        Form.setTabOrder(self.cb_rezult, self.pb_print)
        Form.setTabOrder(self.pb_print, self.pb_ok)
        Form.setTabOrder(self.pb_ok, self.pb_cancel)
        Form.setTabOrder(self.pb_cancel, self.pb_dict)
        Form.setTabOrder(self.pb_dict, self.tw_part1)
        Form.setTabOrder(self.tw_part1, self.tw_part3)
        Form.setTabOrder(self.tw_part3, self.tw_part2)
        Form.setTabOrder(self.tw_part2, self.tw_part4)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Form", "№п/п", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Form", "Группа", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "Категория", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "Фамилия И.О.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Form", "Соответствие требованиям", None, QtGui.QApplication.UnicodeUTF8))
        self.tabwidget.setTabText(self.tabwidget.indexOf(self.tab), QtGui.QApplication.translate("Form", "Оформление", None, QtGui.QApplication.UnicodeUTF8))
        self.tabwidget.setTabText(self.tabwidget.indexOf(self.widget), QtGui.QApplication.translate("Form", "Раздел1", None, QtGui.QApplication.UnicodeUTF8))
        self.tabwidget.setTabText(self.tabwidget.indexOf(self.tab_4), QtGui.QApplication.translate("Form", "Раздел2", None, QtGui.QApplication.UnicodeUTF8))
        self.tabwidget.setTabText(self.tabwidget.indexOf(self.tab_5), QtGui.QApplication.translate("Form", "Раздел3", None, QtGui.QApplication.UnicodeUTF8))
        self.tabwidget.setTabText(self.tabwidget.indexOf(self.tab_3), QtGui.QApplication.translate("Form", "Схемы", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_add.setText(QtGui.QApplication.translate("Form", "Добавить", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_del.setText(QtGui.QApplication.translate("Form", "Удалить", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_dict.setText(QtGui.QApplication.translate("Form", "Словари", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Form", "Должность", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_ok.setText(QtGui.QApplication.translate("Form", "Ok", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Form", "Дата", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Form", "Результат", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_cancel.setText(QtGui.QApplication.translate("Form", "Отмена", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Form", "Звание", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Form", "Фамилия", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_print.setText(QtGui.QApplication.translate("Form", "Печать", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Form", "Сведения о рецензенте", None, QtGui.QApplication.UnicodeUTF8))

