# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'K:\Python\projects\LabRabota_6\widgets\widgetBezAS.ui'
#
# Created: Fri May 13 14:26:33 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(985, 219)
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.cb_psch10 = QtGui.QCheckBox(Form)
        self.cb_psch10.setObjectName("cb_psch10")
        self.gridLayout.addWidget(self.cb_psch10, 7, 3, 1, 1)
        self.cb_psch15 = QtGui.QCheckBox(Form)
        self.cb_psch15.setObjectName("cb_psch15")
        self.gridLayout.addWidget(self.cb_psch15, 7, 4, 1, 1)
        self.cb_psch16 = QtGui.QCheckBox(Form)
        self.cb_psch16.setObjectName("cb_psch16")
        self.gridLayout.addWidget(self.cb_psch16, 3, 5, 1, 1)
        self.cb_psch5 = QtGui.QCheckBox(Form)
        self.cb_psch5.setObjectName("cb_psch5")
        self.gridLayout.addWidget(self.cb_psch5, 7, 2, 1, 1)
        self.cb_psch17 = QtGui.QCheckBox(Form)
        self.cb_psch17.setObjectName("cb_psch17")
        self.gridLayout.addWidget(self.cb_psch17, 4, 5, 1, 1)
        self.cb_psch2 = QtGui.QCheckBox(Form)
        self.cb_psch2.setObjectName("cb_psch2")
        self.gridLayout.addWidget(self.cb_psch2, 4, 2, 1, 1)
        self.cb_psch12 = QtGui.QCheckBox(Form)
        self.cb_psch12.setObjectName("cb_psch12")
        self.gridLayout.addWidget(self.cb_psch12, 4, 4, 1, 1)
        self.cb_psch18 = QtGui.QCheckBox(Form)
        self.cb_psch18.setObjectName("cb_psch18")
        self.gridLayout.addWidget(self.cb_psch18, 5, 5, 1, 1)
        self.cb_psch19 = QtGui.QCheckBox(Form)
        self.cb_psch19.setObjectName("cb_psch19")
        self.gridLayout.addWidget(self.cb_psch19, 6, 5, 1, 1)
        self.pb_vyzov = QtGui.QPushButton(Form)
        self.pb_vyzov.setObjectName("pb_vyzov")
        self.gridLayout.addWidget(self.pb_vyzov, 8, 2, 1, 4)
        self.cb_psch7 = QtGui.QCheckBox(Form)
        self.cb_psch7.setObjectName("cb_psch7")
        self.gridLayout.addWidget(self.cb_psch7, 4, 3, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 9, 1, 1, 1)
        self.cb_psch6 = QtGui.QCheckBox(Form)
        self.cb_psch6.setObjectName("cb_psch6")
        self.gridLayout.addWidget(self.cb_psch6, 3, 3, 1, 1)
        self.cb_psch9 = QtGui.QCheckBox(Form)
        self.cb_psch9.setObjectName("cb_psch9")
        self.gridLayout.addWidget(self.cb_psch9, 6, 3, 1, 1)
        self.cb_psch14 = QtGui.QCheckBox(Form)
        self.cb_psch14.setObjectName("cb_psch14")
        self.gridLayout.addWidget(self.cb_psch14, 6, 4, 1, 1)
        self.cb_psch11 = QtGui.QCheckBox(Form)
        self.cb_psch11.setObjectName("cb_psch11")
        self.gridLayout.addWidget(self.cb_psch11, 3, 4, 1, 1)
        self.cb_psch1 = QtGui.QCheckBox(Form)
        self.cb_psch1.setObjectName("cb_psch1")
        self.gridLayout.addWidget(self.cb_psch1, 3, 2, 1, 1)
        self.cb_psch4 = QtGui.QCheckBox(Form)
        self.cb_psch4.setObjectName("cb_psch4")
        self.gridLayout.addWidget(self.cb_psch4, 6, 2, 1, 1)
        self.cb_psch13 = QtGui.QCheckBox(Form)
        self.cb_psch13.setObjectName("cb_psch13")
        self.gridLayout.addWidget(self.cb_psch13, 5, 4, 1, 1)
        self.cb_psch8 = QtGui.QCheckBox(Form)
        self.cb_psch8.setObjectName("cb_psch8")
        self.gridLayout.addWidget(self.cb_psch8, 5, 3, 1, 1)
        self.cb_psch3 = QtGui.QCheckBox(Form)
        self.cb_psch3.setObjectName("cb_psch3")
        self.gridLayout.addWidget(self.cb_psch3, 5, 2, 1, 1)
        self.lb_soob = QtGui.QLabel(Form)
        self.lb_soob.setText("")
        self.lb_soob.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lb_soob.setObjectName("lb_soob")
        self.gridLayout.addWidget(self.lb_soob, 1, 0, 8, 2)
        self.lb_time = QtGui.QLabel(Form)
        self.lb_time.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_time.setObjectName("lb_time")
        self.gridLayout.addWidget(self.lb_time, 9, 5, 1, 1)
        self.cb_psch20 = QtGui.QCheckBox(Form)
        self.cb_psch20.setObjectName("cb_psch20")
        self.gridLayout.addWidget(self.cb_psch20, 7, 5, 1, 1)
        self.lb_tekStatus = QtGui.QLabel(Form)
        self.lb_tekStatus.setText("")
        self.lb_tekStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_tekStatus.setObjectName("lb_tekStatus")
        self.gridLayout.addWidget(self.lb_tekStatus, 0, 0, 1, 2)
        self.pb_fire = QtGui.QPushButton(Form)
        self.pb_fire.setObjectName("pb_fire")
        self.gridLayout.addWidget(self.pb_fire, 0, 2, 2, 4)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Время реагирования без применения АС", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_psch10.setText(QtGui.QApplication.translate("Form", "ПСЧ-10 (360-8110)", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_psch15.setText(QtGui.QApplication.translate("Form", "ПСЧ-15 (360-8115)", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_psch16.setText(QtGui.QApplication.translate("Form", "ПСЧ-16 (360-8116)", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_psch5.setText(QtGui.QApplication.translate("Form", "ПСЧ-5 (360-8105)", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_psch17.setText(QtGui.QApplication.translate("Form", "ПСЧ-17 (360-8117)", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_psch2.setText(QtGui.QApplication.translate("Form", "ПСЧ-2 (360-8102)", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_psch12.setText(QtGui.QApplication.translate("Form", "ПСЧ-12 (360-8112)", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_psch18.setText(QtGui.QApplication.translate("Form", "ПСЧ-18 (360-8118)", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_psch19.setText(QtGui.QApplication.translate("Form", "ПСЧ-19 (360-8119)", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_vyzov.setText(QtGui.QApplication.translate("Form", "Вызов", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_psch7.setText(QtGui.QApplication.translate("Form", "ПСЧ-7 (360-8107)", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_psch6.setText(QtGui.QApplication.translate("Form", "ПСЧ-6 (360-8106)", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_psch9.setText(QtGui.QApplication.translate("Form", "ПСЧ-9 (360-8109)", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_psch14.setText(QtGui.QApplication.translate("Form", "ПСЧ-14 (360-8114)", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_psch11.setText(QtGui.QApplication.translate("Form", "ПСЧ-11 (360-8111)", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_psch1.setText(QtGui.QApplication.translate("Form", "ПСЧ-1 (360-8101)", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_psch4.setText(QtGui.QApplication.translate("Form", "ПСЧ-4 (360-8104)", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_psch13.setText(QtGui.QApplication.translate("Form", "ПСЧ-13 (360-8113)", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_psch8.setText(QtGui.QApplication.translate("Form", "ПСЧ-8 (360-8108)", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_psch3.setText(QtGui.QApplication.translate("Form", "ПСЧ-3 (360-8103)", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_time.setText(QtGui.QApplication.translate("Form", "00:00:00", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_psch20.setText(QtGui.QApplication.translate("Form", "ПСЧ-20 (360-8120)", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_fire.setText(QtGui.QApplication.translate("Form", "Принять вызов", None, QtGui.QApplication.UnicodeUTF8))

