# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'K:\Python\projects\LabRabota_6\widgets\widgetsAS.ui'
#
# Created: Tue May 17 12:11:53 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1115, 280)
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtGui.QLabel(Form)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 6, 6, 1, 2)
        self.pb_vyzov = QtGui.QPushButton(Form)
        self.pb_vyzov.setObjectName("pb_vyzov")
        self.gridLayout.addWidget(self.pb_vyzov, 3, 2, 1, 11)
        self.label = QtGui.QLabel(Form)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 5, 2, 1, 2)
        self.lb_tekTime = QtGui.QLabel(Form)
        self.lb_tekTime.setText("")
        self.lb_tekTime.setObjectName("lb_tekTime")
        self.gridLayout.addWidget(self.lb_tekTime, 4, 6, 1, 1)
        self.pb_fire = QtGui.QPushButton(Form)
        self.pb_fire.setObjectName("pb_fire")
        self.gridLayout.addWidget(self.pb_fire, 0, 2, 2, 11)
        self.lb_tekStatus = QtGui.QLabel(Form)
        self.lb_tekStatus.setText("")
        self.lb_tekStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_tekStatus.setObjectName("lb_tekStatus")
        self.gridLayout.addWidget(self.lb_tekStatus, 0, 0, 1, 2)
        self.lb_soob = QtGui.QLabel(Form)
        self.lb_soob.setText("")
        self.lb_soob.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lb_soob.setObjectName("lb_soob")
        self.gridLayout.addWidget(self.lb_soob, 1, 0, 7, 2)
        self.splitter_6 = QtGui.QSplitter(Form)
        self.splitter_6.setOrientation(QtCore.Qt.Vertical)
        self.splitter_6.setObjectName("splitter_6")
        self.splitter = QtGui.QSplitter(self.splitter_6)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.cb_psch1 = QtGui.QCheckBox(self.splitter)
        self.cb_psch1.setObjectName("cb_psch1")
        self.cb_psch6 = QtGui.QCheckBox(self.splitter)
        self.cb_psch6.setObjectName("cb_psch6")
        self.cb_psch11 = QtGui.QCheckBox(self.splitter)
        self.cb_psch11.setObjectName("cb_psch11")
        self.cb_psch16 = QtGui.QCheckBox(self.splitter)
        self.cb_psch16.setObjectName("cb_psch16")
        self.splitter_2 = QtGui.QSplitter(self.splitter_6)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.cb_psch2 = QtGui.QCheckBox(self.splitter_2)
        self.cb_psch2.setObjectName("cb_psch2")
        self.cb_psch7 = QtGui.QCheckBox(self.splitter_2)
        self.cb_psch7.setObjectName("cb_psch7")
        self.cb_psch12 = QtGui.QCheckBox(self.splitter_2)
        self.cb_psch12.setObjectName("cb_psch12")
        self.cb_psch17 = QtGui.QCheckBox(self.splitter_2)
        self.cb_psch17.setObjectName("cb_psch17")
        self.splitter_3 = QtGui.QSplitter(self.splitter_6)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.cb_psch3 = QtGui.QCheckBox(self.splitter_3)
        self.cb_psch3.setObjectName("cb_psch3")
        self.cb_psch8 = QtGui.QCheckBox(self.splitter_3)
        self.cb_psch8.setObjectName("cb_psch8")
        self.cb_psch13 = QtGui.QCheckBox(self.splitter_3)
        self.cb_psch13.setObjectName("cb_psch13")
        self.cb_psch18 = QtGui.QCheckBox(self.splitter_3)
        self.cb_psch18.setObjectName("cb_psch18")
        self.splitter_4 = QtGui.QSplitter(self.splitter_6)
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setObjectName("splitter_4")
        self.cb_psch4 = QtGui.QCheckBox(self.splitter_4)
        self.cb_psch4.setObjectName("cb_psch4")
        self.cb_psch9 = QtGui.QCheckBox(self.splitter_4)
        self.cb_psch9.setObjectName("cb_psch9")
        self.cb_psch14 = QtGui.QCheckBox(self.splitter_4)
        self.cb_psch14.setObjectName("cb_psch14")
        self.cb_psch19 = QtGui.QCheckBox(self.splitter_4)
        self.cb_psch19.setObjectName("cb_psch19")
        self.splitter_5 = QtGui.QSplitter(self.splitter_6)
        self.splitter_5.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_5.setObjectName("splitter_5")
        self.cb_psch5 = QtGui.QCheckBox(self.splitter_5)
        self.cb_psch5.setEnabled(True)
        self.cb_psch5.setObjectName("cb_psch5")
        self.cb_psch10 = QtGui.QCheckBox(self.splitter_5)
        self.cb_psch10.setObjectName("cb_psch10")
        self.cb_psch15 = QtGui.QCheckBox(self.splitter_5)
        self.cb_psch15.setObjectName("cb_psch15")
        self.cb_psch20 = QtGui.QCheckBox(self.splitter_5)
        self.cb_psch20.setObjectName("cb_psch20")
        self.gridLayout.addWidget(self.splitter_6, 2, 2, 1, 11)
        self.le_ulica = QtGui.QLineEdit(Form)
        self.le_ulica.setObjectName("le_ulica")
        self.gridLayout.addWidget(self.le_ulica, 5, 4, 1, 1)
        self.splitter_postrad = QtGui.QSplitter(Form)
        self.splitter_postrad.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_postrad.setObjectName("splitter_postrad")
        self.cb_postradavshie = QtGui.QCheckBox(self.splitter_postrad)
        self.cb_postradavshie.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.cb_postradavshie.setText("")
        self.cb_postradavshie.setObjectName("cb_postradavshie")
        self.label_6 = QtGui.QLabel(self.splitter_postrad)
        self.label_6.setObjectName("label_6")
        self.le_postradavshie = QtGui.QLineEdit(self.splitter_postrad)
        self.le_postradavshie.setMouseTracking(True)
        self.le_postradavshie.setObjectName("le_postradavshie")
        self.gridLayout.addWidget(self.splitter_postrad, 7, 4, 1, 1)
        self.splitter_TD = QtGui.QSplitter(Form)
        self.splitter_TD.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_TD.setObjectName("splitter_TD")
        self.splitter_data = QtGui.QSplitter(self.splitter_TD)
        self.splitter_data.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_data.setObjectName("splitter_data")
        self.label_7 = QtGui.QLabel(self.splitter_data)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.lb_tekDatTime = QtGui.QLabel(self.splitter_data)
        self.lb_tekDatTime.setText("")
        self.lb_tekDatTime.setObjectName("lb_tekDatTime")
        self.splitter_time = QtGui.QSplitter(self.splitter_TD)
        self.splitter_time.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.splitter_time.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_time.setObjectName("splitter_time")
        self.gridLayout.addWidget(self.splitter_TD, 4, 4, 1, 1)
        self.label_5 = QtGui.QLabel(Form)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 6, 2, 1, 2)
        self.le_chto = QtGui.QLineEdit(Form)
        self.le_chto.setObjectName("le_chto")
        self.gridLayout.addWidget(self.le_chto, 6, 4, 1, 1)
        self.label_2 = QtGui.QLabel(Form)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 5, 7, 1, 1)
        self.le_dom = QtGui.QLineEdit(Form)
        self.le_dom.setObjectName("le_dom")
        self.gridLayout.addWidget(self.le_dom, 5, 8, 1, 1)
        self.le_FIO = QtGui.QLineEdit(Form)
        self.le_FIO.setObjectName("le_FIO")
        self.gridLayout.addWidget(self.le_FIO, 6, 8, 1, 1)
        self.lb_time = QtGui.QLabel(Form)
        self.lb_time.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_time.setObjectName("lb_time")
        self.gridLayout.addWidget(self.lb_time, 7, 8, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setRowStretch(0, 1)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.le_ulica, self.le_dom)
        Form.setTabOrder(self.le_dom, self.le_chto)
        Form.setTabOrder(self.le_chto, self.le_FIO)
        Form.setTabOrder(self.le_FIO, self.cb_postradavshie)
        Form.setTabOrder(self.cb_postradavshie, self.le_postradavshie)
        Form.setTabOrder(self.le_postradavshie, self.pb_vyzov)
        Form.setTabOrder(self.pb_vyzov, self.pb_fire)
        Form.setTabOrder(self.pb_fire, self.cb_psch15)
        Form.setTabOrder(self.cb_psch15, self.cb_psch19)
        Form.setTabOrder(self.cb_psch19, self.cb_psch7)
        Form.setTabOrder(self.cb_psch7, self.cb_psch4)
        Form.setTabOrder(self.cb_psch4, self.cb_psch9)
        Form.setTabOrder(self.cb_psch9, self.cb_psch13)
        Form.setTabOrder(self.cb_psch13, self.cb_psch14)
        Form.setTabOrder(self.cb_psch14, self.cb_psch1)
        Form.setTabOrder(self.cb_psch1, self.cb_psch18)
        Form.setTabOrder(self.cb_psch18, self.cb_psch3)
        Form.setTabOrder(self.cb_psch3, self.cb_psch20)
        Form.setTabOrder(self.cb_psch20, self.cb_psch16)
        Form.setTabOrder(self.cb_psch16, self.cb_psch5)
        Form.setTabOrder(self.cb_psch5, self.cb_psch8)
        Form.setTabOrder(self.cb_psch8, self.cb_psch6)
        Form.setTabOrder(self.cb_psch6, self.cb_psch2)
        Form.setTabOrder(self.cb_psch2, self.cb_psch10)
        Form.setTabOrder(self.cb_psch10, self.cb_psch17)
        Form.setTabOrder(self.cb_psch17, self.cb_psch12)
        Form.setTabOrder(self.cb_psch12, self.cb_psch11)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Время реагирования с использованием АС", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Form", "ФИО", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_vyzov.setText(QtGui.QApplication.translate("Form", "Отправить", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "Улица", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_fire.setText(QtGui.QApplication.translate("Form", "Принять вызов", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_psch1.setText(QtGui.QApplication.translate("Form", "ПСЧ-1 (360-8101)", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_psch6.setText(QtGui.QApplication.translate("Form", "ПСЧ-6 (360-8106)", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_psch11.setText(QtGui.QApplication.translate("Form", "ПСЧ-11 (360-8111)", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_psch16.setText(QtGui.QApplication.translate("Form", "ПСЧ-16 (360-8116)", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_psch2.setText(QtGui.QApplication.translate("Form", "ПСЧ-2 (360-8102)", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_psch7.setText(QtGui.QApplication.translate("Form", "ПСЧ-7 (360-8107)", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_psch12.setText(QtGui.QApplication.translate("Form", "ПСЧ-12 (360-8112)", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_psch17.setText(QtGui.QApplication.translate("Form", "ПСЧ-17 (360-8117)", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_psch3.setText(QtGui.QApplication.translate("Form", "ПСЧ-3 (360-8103)", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_psch8.setText(QtGui.QApplication.translate("Form", "ПСЧ-8 (360-8108)", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_psch13.setText(QtGui.QApplication.translate("Form", "ПСЧ-13 (360-8113)", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_psch18.setText(QtGui.QApplication.translate("Form", "ПСЧ-18 (360-8118)", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_psch4.setText(QtGui.QApplication.translate("Form", "ПСЧ-4 (360-8104)", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_psch9.setText(QtGui.QApplication.translate("Form", "ПСЧ-9 (360-8109)", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_psch14.setText(QtGui.QApplication.translate("Form", "ПСЧ-14 (360-8114)", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_psch19.setText(QtGui.QApplication.translate("Form", "ПСЧ-19 (360-8119)", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_psch5.setText(QtGui.QApplication.translate("Form", "ПСЧ-5 (360-8105)", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_psch10.setText(QtGui.QApplication.translate("Form", "ПСЧ-10(360-8110)", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_psch15.setText(QtGui.QApplication.translate("Form", "ПСЧ-15 (360-8115)", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_psch20.setText(QtGui.QApplication.translate("Form", "ПСЧ-20 (360-8120)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Form", "Пострадавшие", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Form", "Дата и время:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Form", "Что горит", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "Дом", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_time.setText(QtGui.QApplication.translate("Form", "00:00:00", None, QtGui.QApplication.UnicodeUTF8))

