# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Илья\Dropbox\Programming\Python\projects\vybor_orositela\main_menu.ui'
#
# Created: Fri Mar 17 22:48:39 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(372, 395)
        self.centralwidget = QtGui.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 6, 0, 1, 1)
        self.sb_area_sprinkler = QtGui.QDoubleSpinBox(self.centralwidget)
        self.sb_area_sprinkler.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.sb_area_sprinkler.setDecimals(1)
        self.sb_area_sprinkler.setProperty("value", 12.0)
        self.sb_area_sprinkler.setObjectName("sb_area_sprinkler")
        self.gridLayout.addWidget(self.sb_area_sprinkler, 4, 1, 1, 1)
        self.sb_storage_height = QtGui.QDoubleSpinBox(self.centralwidget)
        self.sb_storage_height.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.sb_storage_height.setDecimals(1)
        self.sb_storage_height.setProperty("value", 1.0)
        self.sb_storage_height.setObjectName("sb_storage_height")
        self.gridLayout.addWidget(self.sb_storage_height, 3, 1, 1, 1)
        self.cb_kategor_VPO = QtGui.QComboBox(self.centralwidget)
        self.cb_kategor_VPO.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cb_kategor_VPO.setObjectName("cb_kategor_VPO")
        self.cb_kategor_VPO.addItem("")
        self.cb_kategor_VPO.addItem("")
        self.gridLayout.addWidget(self.cb_kategor_VPO, 1, 1, 1, 1)
        self.sb_room_height = QtGui.QDoubleSpinBox(self.centralwidget)
        self.sb_room_height.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.sb_room_height.setDecimals(1)
        self.sb_room_height.setSingleStep(1.0)
        self.sb_room_height.setProperty("value", 3.0)
        self.sb_room_height.setObjectName("sb_room_height")
        self.gridLayout.addWidget(self.sb_room_height, 2, 1, 1, 1)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label.setFont(font)
        self.label.setToolTip("")
        self.label.setAutoFillBackground(False)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.pb_raschet = QtGui.QPushButton(self.centralwidget)
        self.pb_raschet.setObjectName("pb_raschet")
        self.gridLayout.addWidget(self.pb_raschet, 7, 0, 1, 2)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.cb_rozetka = QtGui.QComboBox(self.centralwidget)
        self.cb_rozetka.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cb_rozetka.setObjectName("cb_rozetka")
        self.cb_rozetka.addItem("")
        self.cb_rozetka.addItem("")
        self.gridLayout.addWidget(self.cb_rozetka, 6, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.cb_kategory = QtGui.QComboBox(self.centralwidget)
        self.cb_kategory.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cb_kategory.setObjectName("cb_kategory")
        self.cb_kategory.addItem("")
        self.cb_kategory.addItem("")
        self.cb_kategory.addItem("")
        self.cb_kategory.addItem("")
        self.cb_kategory.addItem("")
        self.cb_kategory.addItem("")
        self.gridLayout.addWidget(self.cb_kategory, 0, 1, 1, 1)
        self.cb_pressure = QtGui.QComboBox(self.centralwidget)
        self.cb_pressure.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cb_pressure.setObjectName("cb_pressure")
        self.cb_pressure.addItem("")
        self.cb_pressure.addItem("")
        self.cb_pressure.addItem("")
        self.gridLayout.addWidget(self.cb_pressure, 5, 1, 1, 1)
        self.le_consumption_f = QtGui.QLineEdit(self.centralwidget)
        self.le_consumption_f.setText("")
        self.le_consumption_f.setAlignment(QtCore.Qt.AlignCenter)
        self.le_consumption_f.setObjectName("le_consumption_f")
        self.gridLayout.addWidget(self.le_consumption_f, 11, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 12, 0, 1, 2)
        self.le_intensity = QtGui.QLineEdit(self.centralwidget)
        self.le_intensity.setText("")
        self.le_intensity.setAlignment(QtCore.Qt.AlignCenter)
        self.le_intensity.setObjectName("le_intensity")
        self.gridLayout.addWidget(self.le_intensity, 9, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.centralwidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 10, 0, 1, 1)
        self.label_11 = QtGui.QLabel(self.centralwidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 11, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 9, 0, 1, 1)
        self.le_markirovka = QtGui.QLineEdit(self.centralwidget)
        self.le_markirovka.setAlignment(QtCore.Qt.AlignCenter)
        self.le_markirovka.setObjectName("le_markirovka")
        self.gridLayout.addWidget(self.le_markirovka, 13, 0, 1, 2)
        self.le_consumption_tr = QtGui.QLineEdit(self.centralwidget)
        self.le_consumption_tr.setText("")
        self.le_consumption_tr.setAlignment(QtCore.Qt.AlignCenter)
        self.le_consumption_tr.setObjectName("le_consumption_tr")
        self.gridLayout.addWidget(self.le_consumption_tr, 10, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 14, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 372, 21))
        self.menubar.setObjectName("menubar")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        mainWindow.setWindowTitle(QtGui.QApplication.translate("mainWindow", "Выбор оросителя АУВП", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("mainWindow", "Площадь, защищаемая одним оросителем, м2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("mainWindow", "Давление над диктующим оросителем, МПа", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("mainWindow", "Монтажное положение розетки оросителя", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_kategor_VPO.setItemText(0, QtGui.QApplication.translate("mainWindow", "В1", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_kategor_VPO.setItemText(1, QtGui.QApplication.translate("mainWindow", "В2", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("mainWindow", "Категория по взрывопожаной и пожарной опасности", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("mainWindow", "Группа помещений", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_raschet.setText(QtGui.QApplication.translate("mainWindow", "Расчет", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("mainWindow", "Высота помещений, м", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_rozetka.setItemText(0, QtGui.QApplication.translate("mainWindow", "Вверх", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_rozetka.setItemText(1, QtGui.QApplication.translate("mainWindow", "Вниз", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("mainWindow", "Высота складирования, м", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_kategory.setItemText(0, QtGui.QApplication.translate("mainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_kategory.setItemText(1, QtGui.QApplication.translate("mainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_kategory.setItemText(2, QtGui.QApplication.translate("mainWindow", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_kategory.setItemText(3, QtGui.QApplication.translate("mainWindow", "4.1", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_kategory.setItemText(4, QtGui.QApplication.translate("mainWindow", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_kategory.setItemText(5, QtGui.QApplication.translate("mainWindow", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_pressure.setItemText(0, QtGui.QApplication.translate("mainWindow", "0.1", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_pressure.setItemText(1, QtGui.QApplication.translate("mainWindow", "0.2", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_pressure.setItemText(2, QtGui.QApplication.translate("mainWindow", "0.3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("mainWindow", "Маркировка оросителя", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("mainWindow", "Расход оросителя требуемый, л/с", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("mainWindow", "Расход оросителя фактический, л/с", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("mainWindow", "Интенсивность требуемая, л/(с*м2)", None, QtGui.QApplication.UnicodeUTF8))

